"""
Model Serialization, Report Export, and Inference Code Generator.
"""
from typing import Dict, Any, List, Optional
import io
import joblib
import pandas as pd
import streamlit as st
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder


def serialize_pipeline_to_bytes(
    pipeline: Any,
    model_name: str,
    label_encoder: Optional[LabelEncoder],
    num_cols: List[str],
    cat_cols: List[str],
    task_type: str,
) -> bytes:
    """Serializes the complete trained pipeline with metadata into bytes buffer."""
    bundle = {
        "pipeline": pipeline,
        "model_name": model_name,
        "label_encoder": label_encoder,
        "num_cols": num_cols,
        "cat_cols": cat_cols,
        "task_type": task_type,
    }
    buffer = io.BytesIO()
    joblib.dump(bundle, buffer)
    buffer.seek(0)
    return buffer.getvalue()


def generate_python_inference_code(
    model_name: str,
    num_cols: List[str],
    cat_cols: List[str],
    task_type: str,
) -> str:
    """Generates standalone copy-paste Python code for running inference with the exported pipeline."""
    sample_dict = {}
    for c in num_cols:
        sample_dict[c] = 0.0
    for c in cat_cols:
        sample_dict[c] = "sample_value"

    code = f'''"""
Production Inference Script for {model_name}
Generated by ML Model Comparison Dashboard v3.0
"""
import joblib
import pandas as pd

# 1. Load the exported pipeline bundle
bundle = joblib.load("best_model_pipeline.joblib")
pipeline = bundle["pipeline"]
label_encoder = bundle["label_encoder"]
task_type = bundle["task_type"]

# 2. Define novel input sample
sample_data = {sample_dict}

# 3. Create DataFrame
input_df = pd.DataFrame([sample_data])

# 4. Predict
raw_prediction = pipeline.predict(input_df)[0]

if task_type == "classification" and label_encoder is not None:
    predicted_label = label_encoder.inverse_transform([raw_prediction])[0]
    print(f"Predicted Class: {{predicted_label}}")
    if hasattr(pipeline, "predict_proba"):
        probabilities = pipeline.predict_proba(input_df)[0]
        print(f"Class Probabilities: {{probabilities}}")
else:
    print(f"Predicted Value: {{raw_prediction}}")
'''
    return code


def render_export_tab(
    results: Dict[str, Any],
    pipelines: Dict[str, Any],
    df_leaderboard: pd.DataFrame,
    num_cols: List[str],
    cat_cols: List[str],
    label_encoder: Optional[LabelEncoder],
    task_type: str,
    best_model_name: str,
):
    """Renders the Export tab with downloads and code generator."""
    st.markdown("### 💾 Export Model & Reports")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("#### 📦 Download Serialized Pipeline (`.joblib`)")
        st.caption("Includes fitted preprocessing transformers (imputers, scalers, one-hot encoders) and the trained model.")

        export_model_name = st.selectbox(
            "Select model to export:",
            options=list(pipelines.keys()),
            index=list(pipelines.keys()).index(best_model_name) if best_model_name in pipelines else 0,
            key="export_model_select",
        )
        selected_pipeline = pipelines[export_model_name]

        model_bytes = serialize_pipeline_to_bytes(
            pipeline=selected_pipeline,
            model_name=export_model_name,
            label_encoder=label_encoder,
            num_cols=num_cols,
            cat_cols=cat_cols,
            task_type=task_type,
        )

        st.download_button(
            label=f"⬇️ Download {export_model_name} Pipeline (.joblib)",
            data=model_bytes,
            file_name=f"{export_model_name.lower().replace(' ', '_')}_pipeline.joblib",
            mime="application/octet-stream",
            use_container_width=True,
        )

    with col2:
        st.markdown("#### 📊 Download Evaluation Reports")
        st.caption("Export leaderboard metrics and full classification/regression reports.")

        # Leaderboard CSV
        csv_bytes = df_leaderboard.to_csv(index=True).encode("utf-8")
        st.download_button(
            label="⬇️ Download Leaderboard CSV",
            data=csv_bytes,
            file_name="model_comparison_leaderboard.csv",
            mime="text/csv",
            use_container_width=True,
        )

        # Text report
        report_lines = [f"=== ML Model Comparison Report ({task_type.upper()}) ===\n\n"]
        if task_type == "classification" and label_encoder:
            class_names = [str(c) for c in label_encoder.classes_]
            for name, r in results.items():
                report_lines.append(f"--- Model: {name} ---\n")
                report_lines.append(
                    classification_report(
                        r["y_test"], r["y_pred"], target_names=class_names, zero_division=0
                    )
                )
                report_lines.append("\n")
        else:
            for name, r in results.items():
                report_lines.append(f"--- Model: {name} ---\n")
                report_lines.append(f"R2 Score: {r.get('R2 Score')}\n")
                report_lines.append(f"RMSE: {r.get('RMSE')}\n")
                report_lines.append(f"MAE: {r.get('MAE')}\n\n")

        st.download_button(
            label="⬇️ Download Detailed Report (.txt)",
            data="".join(report_lines).encode("utf-8"),
            file_name="model_evaluation_report.txt",
            mime="text/plain",
            use_container_width=True,
        )

    st.markdown("---")
    st.markdown("#### 💻 Ready-to-use Python Inference Code")
    st.caption("Use this Python script to run inference with your downloaded `.joblib` model.")
    code_str = generate_python_inference_code(export_model_name, num_cols, cat_cols, task_type)
    st.code(code_str, language="python")
